version: '3.8'
services:
db:
    image: mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_DATABASE: Tp04_vue
        MYSQL_USER: root
        MYSQL_PASSWORD: rootpw
php:
    image: php
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./SRC:/var/www/
    links:
        - db